export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNSUPPORTED_LANGUAGE = 'UNSUPPORTED_LANGUAGE',
  UNSUPPORTED_LANGUAGE_PAIR = 'UNSUPPORTED_LANGUAGE_PAIR',
  LANGUAGE_DETECTION_FAILED = 'LANGUAGE_DETECTION_FAILED',
  TEXT_TOO_LONG = 'TEXT_TOO_LONG',
  EMPTY_TEXT = 'EMPTY_TEXT',
  TRANSLATION_FAILED = 'TRANSLATION_FAILED',
  TRANSLATION_TIMEOUT = 'TRANSLATION_TIMEOUT',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
